### ISSUE TITLE
API Spec `allowed_modes` indicates `polyline` is "under construction"

### ISSUE THREAD

**Issue by joshua-dean** [SenteraLLC/ulabel#158]
https://github.com/SenteraLLC/ulabel/blob/f636cdd508f56956fd1c00d7f4ad90ff4a07f84d/api_spec.md?plain=1#L249-L251

Isn't the `polyline` type fairly well-tested at this point? Especially with distance filtering and extension logic, if it had any critical bugs I imagine they would've surfaced by now. 

@TrevorBurgoyne let me know, I can open a PR which updates this portion of the document.

**Comment by TrevorBurgoyne** [comment]
Yeah id say we are safe to remove that qualifier, lol. The main functionality missing from both polyline and polygon modes is the ability to delete individual vertices, but that shouldnt mean its still "under construction". I opened #159 to track that.

Also while you're at it, the other day i realized a [typo](https://github.com/SenteraLLC/ulabel/blob/f636cdd508f56956fd1c00d7f4ad90ff4a07f84d/api_spec.md?plain=1#L45), instances of `init_crop` should be corrected to `initial_crop`, since thats what the argument is actually called.

**Comment by joshua-dean** [comment]
Submitted a draft until #160 is merged.
